### ISSUE TITLE
Issue with parsing longs

### ISSUE THREAD

**Issue by samikrc** [momodi/Json4Scala#1]
Hi,
I love this code - not sure if you are still maintaining this. I am having some issue in parsing a piece of JSON as demonstrated in the following code:
```
val testStr =
    """
      |{
      |    "data": {
      |        "list": {
      |        "name": "Extra",
      |        "id": "576da421ecc0cc7b35cc04cb"
      |        },
      |        "board": {
      |        "shortLink": "H9U5e33P",
      |        "name": "Guest Applications",
      |        "id": "5734da4864b2784117cced07"
      |        },
      |        "card": {
      |        "shortLink": "0lvPpnfJ",
      |        "idShort": 396,
      |        "name": "Fábio O (Fábio) [29-Mar-2017]",
      |        "id": "58dbb3f0a98627ec74baade8",
      |        "pos": 491600.15625
      |        },
      |        "old": {
      |        "pos": 20
      |        }
      |    }
      |}
    """.stripMargin
val json = Json.parse(testStr)
```

I get the following exception:
```
java.lang.NumberFormatException: For input string: "20
    "
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at scala.collection.immutable.StringLike$class.toLong(StringLike.scala:276)
	at scala.collection.immutable.StringOps.toLong(StringOps.scala:29)
	at org.xxx.utils.Json$.parse(Json.scala:219)
	at Main$$anon$1.<init>(JSONParsingTests.scala:32)
	at Main$.main(JSONParsingTests.scala:1)
	at Main.main(JSONParsingTests.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
	at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
	at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
	at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
	at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
	at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
	at scala.tools.nsc.ScriptRunner.scala$tools$nsc$ScriptRunner$$runCompiled(ScriptRunner.scala:175)
	at scala.tools.nsc.ScriptRunner$$anonfun$runScript$1.apply(ScriptRunner.scala:192)
	at scala.tools.nsc.ScriptRunner$$anonfun$runScript$1.apply(ScriptRunner.scala:192)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1$$anonfun$apply$mcZ$sp$1.apply(ScriptRunner.scala:161)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply$mcZ$sp(ScriptRunner.scala:161)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply(ScriptRunner.scala:129)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply(ScriptRunner.scala:129)
	at scala.tools.nsc.util.package$.trackingThreads(package.scala:43)
	at scala.tools.nsc.util.package$.waitingForThreads(package.scala:27)
	at scala.tools.nsc.ScriptRunner.withCompiledScript(ScriptRunner.scala:128)
	at scala.tools.nsc.ScriptRunner.runScript(ScriptRunner.scala:192)
	at scala.tools.nsc.ScriptRunner.runScriptAndCatch(ScriptRunner.scala:205)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:67)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

The line #219 would not match exactly, but it corresponds to #213 in your code. I have tried the following variations for that line:
```
val v = p.substring(i, j).replaceAll("[^a-zA-Z0-9]+","").toLong * minus_flag
val v = p.substring(i, j).replaceAll("[^a-zA-Z0-9]+","").trim.toLong * minus_flag
val v = p.substring(i, j).replaceAll("\\W+","").toLong * minus_flag
```
The most interesting part is that, all of these above variations work in the IntelliJ "Evaluate Expression" window, but fails when actually being executed as part of the code with the same exception. Here, the substring result holds "20\n   ", but in my original code it holds "20\n\t\t\t", with the same exception.

Any ideas?

Regards,
-Samik

**Comment by samikrc** [comment]
Some more tests, and it seems things are not working because of weird IntelliJ settings for running scripts. Each of the variations work fine in compiled codes. You might want to add one of those as a fix.
